import { LoginUseCase } from "../application/auth/LoginUseCase";
import { GestionPadronUseCase } from "../application/alumno/GestionPadronUseCase";
import { GestionDocumentosAlumnoUseCase } from "../application/alumno/GestionDocumentosAlumnoUseCase";
import { GestionHorasAlumnoUseCase } from "../application/alumno/GestionHorasAlumnoUseCase";
import { GestionReportesAlumnoUseCase } from "../application/alumno/GestionReportesAlumnoUseCase";
import { GestionAsesorUseCase } from "../application/asesor/GestionAsesorUseCase";
import { GestionAsignacionAsesoresUseCase } from "../application/coordinador/GestionAsignacionAsesoresUseCase";
import { GestionConfirmacionAsignacionesUseCase } from "../application/coordinador/GestionConfirmacionAsignacionesUseCase";
import { GestionLiberacionUseCase } from "../application/coordinador/GestionLiberacionUseCase";
import { GestionEmpresasRevisionUseCase } from "../application/coord-unidades/GestionEmpresasRevisionUseCase";
import { GestionVacantesRevisionUseCase } from "../application/coord-unidades/GestionVacantesRevisionUseCase";
import { GestionConfiguracionUseCase } from "../application/configuracion/GestionConfiguracionUseCase";
import { GestionDocumentacionEmpresaUseCase } from "../application/empresa/GestionDocumentacionEmpresaUseCase";
import { GestionRevisionDocumentalUseCase } from "../application/documentos/GestionRevisionDocumentalUseCase";
import { ListarRolesUseCase } from "../application/roles/ListarRolesUseCase";
import { GestionSeguimientoPracticasUseCase } from "../application/seguimiento/GestionSeguimientoPracticasUseCase";
import { GestionNotificacionesUseCase } from "../application/notificaciones/GestionNotificacionesUseCase";
import { GestionAlumnosUnidadUseCase } from "../application/unidad/GestionAlumnosUnidadUseCase";
import { GestionHorasUnidadUseCase } from "../application/unidad/GestionHorasUnidadUseCase";
import { GestionVacantesUnidadUseCase } from "../application/unidad/GestionVacantesUnidadUseCase";
import { GestionUsuariosUseCase } from "../application/usuarios/GestionUsuariosUseCase";
import { AuthHttpRepository } from "../infrastructure/auth/AuthHttpRepository";
import { PadronHttpRepository } from "../infrastructure/alumno/PadronHttpRepository";
import { DocumentoAlumnoHttpRepository } from "../infrastructure/alumno/DocumentoAlumnoHttpRepository";
import { HorasAlumnoHttpRepository } from "../infrastructure/alumno/HorasAlumnoHttpRepository";
import { ReporteAlumnoHttpRepository } from "../infrastructure/alumno/ReporteAlumnoHttpRepository";
import { AsesorHttpRepository } from "../infrastructure/asesor/AsesorHttpRepository";
import { AsignacionAsesorHttpRepository } from "../infrastructure/coordinador/AsignacionAsesorHttpRepository";
import { ConfirmacionAsignacionHttpRepository } from "../infrastructure/coordinador/ConfirmacionAsignacionHttpRepository";
import { LiberacionHttpRepository } from "../infrastructure/coordinador/LiberacionHttpRepository";
import { EmpresaRevisionHttpRepository } from "../infrastructure/coord-unidades/EmpresaRevisionHttpRepository";
import { VacanteRevisionHttpRepository } from "../infrastructure/coord-unidades/VacanteRevisionHttpRepository";
import { ConfiguracionHttpRepository } from "../infrastructure/configuracion/ConfiguracionHttpRepository";
import { DocumentacionEmpresaHttpRepository } from "../infrastructure/empresa/DocumentacionEmpresaHttpRepository";
import { RevisionDocumentalHttpRepository } from "../infrastructure/documentos/RevisionDocumentalHttpRepository";
import { RolHttpRepository } from "../infrastructure/roles/RolHttpRepository";
import { SeguimientoPracticasHttpRepository } from "../infrastructure/seguimiento/SeguimientoPracticasHttpRepository";
import { NotificacionHttpRepository } from "../infrastructure/notificaciones/NotificacionHttpRepository";
import { AlumnoUnidadHttpRepository } from "../infrastructure/unidad/AlumnoUnidadHttpRepository";
import { HorasUnidadHttpRepository } from "../infrastructure/unidad/HorasUnidadHttpRepository";
import { VacanteUnidadHttpRepository } from "../infrastructure/unidad/VacanteUnidadHttpRepository";
import { UsuarioHttpRepository } from "../infrastructure/usuarios/UsuarioHttpRepository";

const authRepository = new AuthHttpRepository();
const padronRepository = new PadronHttpRepository();
const documentoAlumnoRepository = new DocumentoAlumnoHttpRepository();
const horasAlumnoRepository = new HorasAlumnoHttpRepository();
const reporteAlumnoRepository = new ReporteAlumnoHttpRepository();
const asesorRepository = new AsesorHttpRepository();
const asignacionAsesorRepository = new AsignacionAsesorHttpRepository();
const confirmacionAsignacionRepository = new ConfirmacionAsignacionHttpRepository();
const liberacionRepository = new LiberacionHttpRepository();
const empresaRevisionRepository = new EmpresaRevisionHttpRepository();
const vacanteRevisionRepository = new VacanteRevisionHttpRepository();
const configuracionRepository = new ConfiguracionHttpRepository();
const documentacionEmpresaRepository = new DocumentacionEmpresaHttpRepository();
const revisionDocumentalRepository = new RevisionDocumentalHttpRepository();
const usuarioRepository = new UsuarioHttpRepository();
const rolRepository = new RolHttpRepository();
const seguimientoPracticasRepository = new SeguimientoPracticasHttpRepository();
const notificacionRepository = new NotificacionHttpRepository();
const alumnoUnidadRepository = new AlumnoUnidadHttpRepository();
const horasUnidadRepository = new HorasUnidadHttpRepository();
const vacanteUnidadRepository = new VacanteUnidadHttpRepository();

export const loginUseCase = new LoginUseCase(authRepository);
export const gestionPadronUseCase = new GestionPadronUseCase(padronRepository);
export const gestionDocumentosAlumnoUseCase = new GestionDocumentosAlumnoUseCase(documentoAlumnoRepository);
export const gestionHorasAlumnoUseCase = new GestionHorasAlumnoUseCase(horasAlumnoRepository);
export const gestionReportesAlumnoUseCase = new GestionReportesAlumnoUseCase(reporteAlumnoRepository);
export const gestionAsesorUseCase = new GestionAsesorUseCase(asesorRepository);
export const gestionAsignacionAsesoresUseCase = new GestionAsignacionAsesoresUseCase(asignacionAsesorRepository);
export const gestionConfirmacionAsignacionesUseCase = new GestionConfirmacionAsignacionesUseCase(confirmacionAsignacionRepository);
export const gestionLiberacionUseCase = new GestionLiberacionUseCase(liberacionRepository);
export const gestionEmpresasRevisionUseCase = new GestionEmpresasRevisionUseCase(empresaRevisionRepository);
export const gestionVacantesRevisionUseCase = new GestionVacantesRevisionUseCase(vacanteRevisionRepository);
export const gestionConfiguracionUseCase = new GestionConfiguracionUseCase(configuracionRepository);
export const gestionDocumentacionEmpresaUseCase = new GestionDocumentacionEmpresaUseCase(documentacionEmpresaRepository);
export const gestionRevisionDocumentalUseCase = new GestionRevisionDocumentalUseCase(revisionDocumentalRepository);
export const gestionUsuariosUseCase = new GestionUsuariosUseCase(usuarioRepository);
export const listarRolesUseCase = new ListarRolesUseCase(rolRepository);
export const gestionSeguimientoPracticasUseCase = new GestionSeguimientoPracticasUseCase(seguimientoPracticasRepository);
export const gestionNotificacionesUseCase = new GestionNotificacionesUseCase(notificacionRepository);
export const gestionAlumnosUnidadUseCase = new GestionAlumnosUnidadUseCase(alumnoUnidadRepository);
export const gestionHorasUnidadUseCase = new GestionHorasUnidadUseCase(horasUnidadRepository);
export const gestionVacantesUnidadUseCase = new GestionVacantesUnidadUseCase(vacanteUnidadRepository);
